version: 1.0.{build}

image: Visual Studio 2022

install:
  - ps: Install-Product node 20

build_script:
  - cmd: yarn install
  - cmd: yarn build

test_script:
  - cmd: echo "No tests"

deploy_script:
  - ps: |
      git config --global user.email "evgenia.maksimovna00@gmail.com"
      git config --global user.name "Евгения"
      npx gh-pages -d dist -r https://%GITHUB_TOKEN%@github.com/FilSado/task-board.git

